FROM node:20-alpine

WORKDIR /app

# Copy db.json into the container
COPY db.json ./db.json

# Install json-server globally
RUN npm install -g json-server@0.17.4

EXPOSE 3001

CMD ["json-server", "--watch", "db.json", "--host", "0.0.0.0", "--port", "3001"]
